/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 as long as the process is running. Never touches the database.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 once the database is reachable and the first snapshot has been built.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List buildings */
        get: operations["listBuildings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{code}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Floor geometry of a building
         * @description The full `MapSpec` for a building: every floor with its outline, zones, corridors,
         *     rooms (SVG path, bbox, label anchor), cores, landmarks and entrances.
         *
         *     This document is generated from `packages/map-data/svg/floor-{n}.svg` by
         *     `pnpm map:build` into `packages/map-data/building-a.json` and seeded into the
         *     database, so the rendered map and the room table can never drift apart.
         *     The payload is immutable between deploys and carries a strong `ETag`.
         *
         */
        get: operations["getBuildingMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{code}/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Board snapshot
         * @description The complete board state at an instant: statistics, the live state of every room,
         *     the `NOW` list (phase `live` or `ending`, sorted by `endAt`) and the `NEXT` list
         *     (phase `soon` or `upcoming` starting within the 90-minute horizon, sorted by `startAt`).
         *
         *     Used for server-side rendering of the first frame, for time travel (`at`) and as the
         *     payload of the SSE `snapshot` event. Without `at` and `date` the server uses its own
         *     `Clock` "now".
         *
         */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{code}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All sessions of one day
         * @description Every materialised session of the given local building date, sorted by `startAt`.
         *     Backs the time-travel scrubber (slot ticks and the occupancy heat strip) and the
         *     room detail panel. Defaults to the current local building date.
         *
         */
        get: operations["getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{code}/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sessions of one room for a day
         * @description Sessions that take place in this room on the given date, sorted by `startAt`.
         *     A session moved *into* this room appears here (its `roomCode` equals `code`);
         *     a session moved *out of* it does not.
         *
         */
        get: operations["getRoomDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teachers/{id}/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions of one teacher for a day */
        get: operations["getTeacherDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{code}/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions of one student group for a day */
        get: operations["getGroupDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unified search
         * @description Case-insensitive prefix/substring search over teachers, student groups, rooms and
         *     courses. At most 5 hits per kind unless `limit` says otherwise. Selecting a hit in
         *     the UI highlights the matching rooms on the map and filters the board.
         *
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream
         * @description A `text/event-stream` of board updates for one building. The connection stays open;
         *     the server never buffers (Caddy is configured with `flush_interval -1`).
         *
         *     Event names and their `data` payloads:
         *
         *     | event | data | when |
         *     |---|---|---|
         *     | `snapshot` | a `Snapshot` object | immediately on connect, on every phase transition, and after every admin override |
         *     | `announcement` | an `Announcement` object | when a new ticker announcement is posted |
         *     | `heartbeat` | `{ "at": "<RFC3339 date-time>" }` | every 25 seconds, so proxies keep the connection open |
         *
         *     Clients that see no `heartbeat` for 30 s should treat the connection as
         *     `reconnecting`. `EventSource` reconnects on its own; after a reconnect the client
         *     should refetch `GET /buildings/{code}/board` once, because snapshots are full states
         *     and nothing is lost by re-reading one.
         *
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server clock
         * @description The server's current instant and clock mode. The client uses it once at startup to
         *     compute its own drift from the server, so the header clock and every countdown stay
         *     in step with the engine even in `fixed` and `offset` demo modes.
         *
         */
        get: operations["getTime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a session override
         * @description Demo admin API. Applies a point change to one date: `cancel`, `move`, `delay`,
         *     `reassign_teacher` or `extra`. The board is invalidated and rebuilt immediately, so
         *     every connected SSE client sees the result in under a second.
         *
         *     For every kind except `extra` the target session is identified by `lessonId` **or**
         *     `sessionId` (`"{lessonId}:{date}"`). For `extra`, supply `courseCode`, `roomCode`,
         *     `teacherId`, `slotIdx` and `groupCodes` instead.
         *
         */
        post: operations["createOverride"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overrides/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Roll back an override
         * @description Deletes the override and rebuilds the board immediately.
         */
        delete: operations["deleteOverride"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post a ticker announcement
         * @description Publishes a line to the bottom ticker of every connected client as an SSE
         *     `announcement` event. When `startsAt` / `endsAt` are omitted the window is
         *     `now … now + ttlMinutes`.
         *
         */
        post: operations["createAnnouncement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Machine-readable error detail. */
        ErrorBody: {
            /**
             * @description Stable error code.
             * @enum {string}
             */
            code: "not_found" | "bad_request" | "unauthorized" | "conflict" | "internal";
            /** @description Human-readable explanation. Not localised; UI copy comes from the client. */
            message: string;
        };
        /** @description The single error envelope used by every non-2xx response. */
        Error: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * @description What a space is. Only `lecture`, `seminar`, `lab` and (rarely) `coworking` rooms are
         *     ever `schedulable`; `void` spaces (the atrium, the double-height opening over the
         *     Skywalkers lab) are drawn as holes in the slab and never carry a status.
         *
         * @enum {string}
         */
        RoomType: "lecture" | "seminar" | "lab" | "coworking" | "admin" | "service" | "void";
        /**
         * @description Which part of the floor plate the space sits in.
         * @enum {string}
         */
        Wing: "north" | "south" | "core";
        /**
         * @description Pedagogical form of a session.
         * @enum {string}
         */
        LessonType: "lecture" | "practice" | "lab";
        /**
         * @description What happened to a session as data, independent of the wall clock.
         *     `moved` means the room changed; `delayed` means the times were shifted.
         *
         * @enum {string}
         */
        SessionStatus: "scheduled" | "cancelled" | "moved" | "delayed";
        /**
         * @description Where a session sits relative to "now", computed by the Go engine:
         *     `upcoming` → `soon` (within `SOON_WINDOW`, default 10 min) → `live` →
         *     `ending` (last `ENDING_WINDOW`, default 5 min) → `done`.
         *     A cancelled session is always `cancelled` and never occupies its room.
         *
         * @enum {string}
         */
        Phase: "upcoming" | "soon" | "live" | "ending" | "done" | "cancelled";
        /**
         * @description The state of a room, derived from its owning session with priority
         *     `live`/`ending` > `soon` > `free`.
         *
         * @enum {string}
         */
        RoomPhase: "free" | "soon" | "live" | "ending";
        /**
         * @description The kind of point change applied to one date.
         *     `extra` adds a one-off session that has no lesson template.
         *
         * @enum {string}
         */
        OverrideKind: "cancel" | "move" | "delay" | "reassign_teacher" | "extra";
        /**
         * @description Visual weight of a ticker announcement.
         * @enum {string}
         */
        Severity: "info" | "warning" | "alert";
        /**
         * @description How the server produces "now": `real` = wall clock, `fixed` = always `CLOCK_FIXED_AT`
         *     (e2e and screenshots), `offset` = wall clock shifted by `CLOCK_OFFSET` (demo).
         *
         * @enum {string}
         */
        ClockMode: "real" | "fixed" | "offset";
        /**
         * @description Parity of the current teaching week, counted from `semester.starts_on`.
         * @enum {string}
         */
        WeekParity: "odd" | "even";
        /** @description One building of the campus. */
        Building: {
            /**
             * @description Short unique code used everywhere in the API.
             * @example A
             */
            code: string;
            /** @example Main Academic Building */
            name: string;
            /**
             * @description IANA time zone; every local date and slot time is resolved through it.
             * @example Asia/Almaty
             */
            timezone: string;
            /**
             * Format: int32
             * @description Number of floors.
             * @example 4
             */
            floors: number;
        };
        /** @description Axis-aligned bounding box in the floor's `viewBox` coordinate system. */
        BBox: {
            x: number;
            y: number;
            w: number;
            h: number;
        };
        /** @description A point in the floor's `viewBox` coordinate system. */
        Point: {
            x: number;
            y: number;
        };
        /** @description One space on a floor, as geometry plus the attributes the seed writes into `rooms`.
         *     `id` is a deterministic UUID v5 of `campuslive:room:{code}`, so the web app and the
         *     database agree on room identity even before the database exists.
         *      */
        MapRoom: {
            /**
             * Format: uuid
             * @description Deterministic UUID v5 derived from the room code.
             */
            id: string;
            /**
             * @description Unique room code within the building.
             * @example 213
             */
            code: string;
            /** @example Lecture Hall "Gamma" */
            name: string;
            type: components["schemas"]["RoomType"];
            wing: components["schemas"]["Wing"];
            /**
             * Format: int32
             * @description Seats. Absent for spaces where capacity is meaningless (corridors, voids, cores).
             */
            capacity?: number;
            /** @description Whether lessons may be placed here. Non-schedulable rooms are drawn but never coloured by status. */
            schedulable: boolean;
            /** @description SVG path data (`d`) of the room polygon, closed with `Z`. */
            path: string;
            bbox: components["schemas"]["BBox"];
            label: components["schemas"]["Point"];
        };
        /** @description A tinted background band (wing or corridor). Purely decorative. */
        MapZone: {
            /** @example zone-hall */
            id: string;
            /** @description SVG path data (`d`). */
            path: string;
        };
        /** @description A vertical circulation core (stairs + elevators) on the east strip. */
        MapCore: {
            /**
             * @description Position of the core on the plate.
             * @enum {string}
             */
            id: "core-n" | "core-s";
            /**
             * @description The room code the same core carries in `rooms`, e.g. `CORE-N2`.
             * @example CORE-N2
             */
            code: string;
            /** @example Stairs SF-1 + Elevators */
            name: string;
            /** @description SVG path data (`d`). */
            path: string;
            bbox: components["schemas"]["BBox"];
            label: components["schemas"]["Point"];
        };
        /** @description A glyph anchor on the plan (stairs, elevator, …). */
        MapLandmark: {
            /**
             * @description Glyph family, e.g. `stairs`.
             * @example stairs
             */
            kind: string;
            /** @example stairs-sf1 */
            id: string;
            x: number;
            y: number;
        };
        /** @description A door in the façade. `x`/`y` is the centroid of `path`. */
        MapEntrance: {
            /** @example entrance-w */
            id: string;
            x: number;
            y: number;
            /** @description True for the main (west) entrance. */
            main: boolean;
            /** @description SVG path data (`d`). */
            path: string;
        };
        /** @description One floor plate. */
        MapFloor: {
            /**
             * Format: int32
             * @example 2
             */
            number: number;
            /**
             * @description Key linking the geometry to the `floors.plan_key` column.
             * @example a-f2
             */
            planKey: string;
            /** @description SVG path data (`d`) of the floor slab silhouette. */
            outline: string;
            zones: components["schemas"]["MapZone"][];
            corridors: components["schemas"]["MapZone"][];
            /** @description Every space on the floor, including cores and voids. */
            rooms: components["schemas"]["MapRoom"][];
            cores: components["schemas"]["MapCore"][];
            landmarks: components["schemas"]["MapLandmark"][];
            entrances: components["schemas"]["MapEntrance"][];
            /** @description SVG path data (`d`) of the atrium void. Present on floor 2 only. */
            atrium?: string;
        };
        /** @description The full geometry of a building. Generated by `pnpm map:build` from
         *     `packages/map-data/svg/floor-{n}.svg` into `packages/map-data/building-a.json`;
         *     served verbatim by `getBuildingMap` and read by `cmd/seed`.
         *      */
        MapSpec: {
            /**
             * @description Building code.
             * @example A
             */
            building: string;
            /** @example Main Academic Building */
            name: string;
            /** @example Asia/Almaty */
            timezone: string;
            /**
             * @description SVG viewBox as `[minX, minY, width, height]`, shared by every floor.
             * @example [
             *       0,
             *       0,
             *       600,
             *       1000
             *     ]
             */
            viewBox: number[];
            floors: components["schemas"]["MapFloor"][];
        };
        /** @description Compact teacher reference embedded in session views. */
        TeacherRef: {
            /** Format: uuid */
            id: string;
            /**
             * @description Board-sized name, e.g. `Ахметов Д.Б.`
             * @example Ахметов Д.Б.
             */
            shortName: string;
            fullName?: string;
            department?: string;
        };
        /** @description One materialised session as the board and the map show it.
         *
         *     **Room semantics.** `roomId` / `roomCode` / `floor` always describe the **effective**
         *     room — where the session actually happens. For a session with `status = moved`,
         *     `movedFromRoomCode` holds the original room; the board keeps the row in the original
         *     room's column and renders a `MOVED → {roomCode}` pill, while the map colours the new room.
         *
         *     **Time semantics.** `startAt` / `endAt` are absolute UTC instants that already include
         *     any delay (`status = delayed`, `delayMinutes` says by how much). Clients must not
         *     re-apply the delay.
         *
         *     **Identity.** `sessionId` is `"{lessonId}:{date}"` for a templated session and
         *     `"x:{overrideId}"` for an `extra` one; `lessonId` is absent for `extra` sessions.
         *      */
        SessionView: {
            /**
             * @description `"{lessonId}:{date}"`, or `"x:{overrideId}"` for an extra session.
             * @example 8f1c...:2026-09-08
             */
            sessionId: string;
            /**
             * Format: uuid
             * @description The lesson template this session comes from. Absent for `extra` sessions.
             */
            lessonId?: string;
            /** @example CS201 */
            courseCode: string;
            /** @example Databases */
            courseTitle: string;
            lessonType: components["schemas"]["LessonType"];
            teacher: components["schemas"]["TeacherRef"];
            /**
             * @description Student group codes attending, in display order.
             * @example [
             *       "ПО2308",
             *       "ПО2309"
             *     ]
             */
            groups: string[];
            /**
             * Format: uuid
             * @description Effective room id (after a move).
             */
            roomId: string;
            /**
             * @description Effective room code (after a move).
             * @example 214
             */
            roomCode: string;
            /**
             * Format: int32
             * @description Floor of the effective room.
             */
            floor: number;
            /**
             * Format: date-time
             * @description Absolute start, delay already applied.
             */
            startAt: string;
            /**
             * Format: date-time
             * @description Absolute end, delay already applied.
             */
            endAt: string;
            status: components["schemas"]["SessionStatus"];
            phase: components["schemas"]["Phase"];
            /** @description True when another session overlaps the same room; the earlier start owns the room. */
            conflict: boolean;
            /**
             * @description Original room code when `status = moved`.
             * @example 213
             */
            movedFromRoomCode?: string;
            /**
             * Format: int32
             * @description Minutes the session was pushed back when `status = delayed`.
             */
            delayMinutes?: number;
            /** @description Free-text note attached by the override that changed this session. */
            note?: string;
        };
        /** @description The live state of one room. `current` is the session owning the room right now,
         *     `next` the following one today. `freeUntil` is the start of `next` when the room is
         *     free, and `null` when the room is busy or has nothing left today.
         *      */
        RoomLiveState: {
            /** Format: uuid */
            roomId: string;
            /** @example 213 */
            roomCode: string;
            /** Format: int32 */
            floor: number;
            phase: components["schemas"]["RoomPhase"];
            current?: components["schemas"]["SessionView"];
            next?: components["schemas"]["SessionView"];
            /**
             * Format: date-time
             * @description When the free room is taken next. Nullable: the server sends `null` (and Go emits a
             *     nil pointer) when the room is busy or has nothing left today. Not expressed as a
             *     `["string","null"]` union because `oapi-codegen` cannot yet generate 3.1 type unions.
             *
             */
            freeUntil?: string;
        };
        /** @description Header and legend counters. */
        Stats: {
            /**
             * Format: int32
             * @description Number of schedulable rooms in the building.
             */
            roomsTotal: number;
            /**
             * Format: int32
             * @description Schedulable rooms whose phase is `live` or `ending`.
             */
            roomsBusy: number;
            /** Format: int32 */
            sessionsToday: number;
            /** Format: int32 */
            sessionsDone: number;
        };
        /** @description The complete board state at `at`. Sent as the body of `getBoard` and as the payload of
         *     the SSE `snapshot` event — always a full state, never a delta, so a dropped message
         *     costs nothing.
         *      */
        Snapshot: {
            /** @example A */
            building: string;
            /**
             * Format: date-time
             * @description The instant this snapshot describes.
             */
            at: string;
            /**
             * @description Local building date of `at`. Shown in the header.
             * @example 2026-09-08
             */
            date: string;
            /**
             * Format: int32
             * @description 1-based teaching week counted from `semester.starts_on`.
             * @example 3
             */
            weekNumber: number;
            weekParity: components["schemas"]["WeekParity"];
            /**
             * Format: date-time
             * @description The earliest instant after `at` at which any session crosses a phase boundary.
             *     The scheduler sleeps until then (capped at 5 minutes). Nullable: `null` when nothing
             *     is left to happen today.
             *
             */
            nextTransitionAt?: string;
            stats: components["schemas"]["Stats"];
            /** @description Live state of every room of the building, schedulable or not. */
            rooms: components["schemas"]["RoomLiveState"][];
            /** @description Sessions in phase `live` or `ending`, sorted by `endAt`. */
            now: components["schemas"]["SessionView"][];
            /** @description Sessions in phase `soon` or `upcoming` starting within the 90-minute horizon (cancelled and moved ones included), sorted by `startAt`. */
            next: components["schemas"]["SessionView"][];
        };
        /** @description Every session of one building on one local date, sorted by `startAt`. */
        Timeline: {
            /** @example A */
            building: string;
            /** @example 2026-09-08 */
            date: string;
            sessions: components["schemas"]["SessionView"][];
        };
        /** @description Sessions of one room, teacher or group on one local date, sorted by `startAt`. */
        DaySessions: {
            /** @example 2026-09-08 */
            date: string;
            sessions: components["schemas"]["SessionView"][];
        };
        SearchTeacher: {
            /** Format: uuid */
            id: string;
            /** @example Ахметов Д.Б. */
            shortName: string;
            fullName?: string;
            department?: string;
        };
        SearchGroup: {
            /** Format: uuid */
            id: string;
            /** @example ПО2308 */
            code: string;
            program?: string;
            /** Format: int32 */
            courseYear?: number;
        };
        SearchRoom: {
            /** Format: uuid */
            id: string;
            /** @example 213 */
            code: string;
            name: string;
            /** Format: int32 */
            floor: number;
            type: components["schemas"]["RoomType"];
        };
        SearchCourse: {
            /** Format: uuid */
            id: string;
            /** @example CS201 */
            code: string;
            title: string;
        };
        /** @description Search hits grouped by kind. Every array is present, possibly empty. */
        SearchResult: {
            teachers: components["schemas"]["SearchTeacher"][];
            groups: components["schemas"]["SearchGroup"][];
            rooms: components["schemas"]["SearchRoom"][];
            courses: components["schemas"]["SearchCourse"][];
        };
        /** @description Server "now" and how it is produced. */
        TimeInfo: {
            /**
             * Format: date-time
             * @description The server's current instant according to the configured `Clock`.
             */
            now: string;
            mode: components["schemas"]["ClockMode"];
            /**
             * @description Go duration applied in `offset` mode, e.g. `-3h20m`.
             * @example -3h20m
             */
            offset?: string;
            /**
             * @description IANA time zone of the default building.
             * @example Asia/Almaty
             */
            timezone: string;
        };
        /** @description A point change for one local date.
         *
         *     * `cancel` — target session only.
         *     * `move` — target session + `newRoomCode`.
         *     * `delay` — target session + `delayMinutes`.
         *     * `reassign_teacher` — target session + `newTeacherId`.
         *     * `extra` — no target; supply `courseCode`, `roomCode`, `teacherId`, `slotIdx` and `groupCodes`.
         *
         *     For every kind except `extra`, the target session is identified by `lessonId` **or**
         *     `sessionId`; supplying neither is a `bad_request`.
         *      */
        OverrideRequest: {
            /**
             * @description Local building date the change applies to.
             * @example 2026-09-08
             */
            date: string;
            kind: components["schemas"]["OverrideKind"];
            /**
             * Format: uuid
             * @description Target lesson template. One of `lessonId` / `sessionId` is required for non-`extra` kinds.
             */
            lessonId?: string;
            /** @description Target session id (`"{lessonId}:{date}"`). Alternative to `lessonId`. */
            sessionId?: string;
            /**
             * @description Required for `move`.
             * @example 214
             */
            newRoomCode?: string;
            /**
             * Format: uuid
             * @description Required for `reassign_teacher`.
             */
            newTeacherId?: string;
            /**
             * Format: int32
             * @description Required for `delay`. Positive minutes.
             * @example 15
             */
            delayMinutes?: number;
            /**
             * @description Required for `extra`.
             * @example CS201
             */
            courseCode?: string;
            /**
             * @description Required for `extra`.
             * @example 213
             */
            roomCode?: string;
            /**
             * Format: uuid
             * @description Required for `extra`.
             */
            teacherId?: string;
            /**
             * Format: int32
             * @description Required for `extra`. 1-based time-slot index of the building.
             * @example 4
             */
            slotIdx?: number;
            /**
             * @description Student groups attending an `extra` session.
             * @example [
             *       "ПО2308"
             *     ]
             */
            groupCodes?: string[];
            /** @description Free-text note surfaced on the board row and in the room panel. */
            note?: string;
        };
        /** @description A stored override. */
        Override: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Absent for `extra` overrides.
             */
            lessonId?: string;
            /** @example 2026-09-08 */
            date: string;
            kind: components["schemas"]["OverrideKind"];
            newRoomCode?: string;
            /** Format: uuid */
            newTeacherId?: string;
            /** Format: int32 */
            delayMinutes?: number;
            courseCode?: string;
            roomCode?: string;
            /** Format: int32 */
            slotIdx?: number;
            note?: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description A new ticker line. Omit `startsAt`/`endsAt` to use `now … now + ttlMinutes`. */
        AnnouncementRequest: {
            /**
             * @description Building code. Defaults to `A`.
             * @default A
             * @example A
             */
            building: string;
            /** @example Open lecture in the Assembly Hall at 18:00 */
            text: string;
            severity?: components["schemas"]["Severity"];
            /**
             * Format: date-time
             * @description Start of the display window. Defaults to now.
             */
            startsAt?: string;
            /**
             * Format: date-time
             * @description End of the display window. Defaults to `startsAt + ttlMinutes`.
             */
            endsAt?: string;
            /**
             * Format: int32
             * @description Display duration in minutes when `endsAt` is omitted.
             * @default 30
             * @example 30
             */
            ttlMinutes: number;
        };
        /** @description A ticker line. Also the payload of the SSE `announcement` event. */
        Announcement: {
            /** Format: uuid */
            id: string;
            /** @example A */
            building: string;
            text: string;
            severity: components["schemas"]["Severity"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
        };
        /** @description Liveness payload. */
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        /** @description Readiness payload; `status` is `ok` only when both checks pass. */
        Ready: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @description The database answered a ping. */
            db: boolean;
            /** @description The first board snapshot has been built. */
            snapshot: boolean;
        };
    };
    responses: {
        /** @description The payload has not changed since the supplied `ETag`. */
        NotModified: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Malformed request. `error.code` is `bad_request`. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or wrong `X-Api-Key`. `error.code` is `unauthorized`. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such building, room, teacher, group or override. `error.code` is `not_found`. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request conflicts with existing data. `error.code` is `conflict`. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Building code, e.g. `A`. */
        BuildingCodePath: string;
        /** @description Absolute instant (RFC 3339) to evaluate the board at. Omit for the server's own "now".
         *     Used by the time-travel scrubber.
         *      */
        AtQuery: string;
        /** @description Local building date `YYYY-MM-DD`. Defaults to the building's current local date. */
        DateQuery: string;
        /** @description Previously received `ETag`. The server answers `304` when the payload is unchanged. */
        IfNoneMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Strong entity tag of the payload. Send it back as `If-None-Match`. */
        ETag: string;
        /** @description Caching policy for this payload. */
        CacheControl: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready to serve traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ready"];
                };
            };
            /** @description Service is not ready yet. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ready"];
                };
            };
        };
    };
    listBuildings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All known buildings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"][];
                };
            };
        };
    };
    getBuildingMap: {
        parameters: {
            query?: never;
            header?: {
                /** @description Previously received `ETag`. The server answers `304` when the payload is unchanged. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                /** @description Building code, e.g. `A`. */
                code: components["parameters"]["BuildingCodePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Floor geometry. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapSpec"];
                };
            };
            304: components["responses"]["NotModified"];
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getBoard: {
        parameters: {
            query?: {
                /** @description Absolute instant (RFC 3339) to evaluate the board at. Omit for the server's own "now".
                 *     Used by the time-travel scrubber.
                 *      */
                at?: components["parameters"]["AtQuery"];
                /** @description Local building date `YYYY-MM-DD`. Defaults to the building's current local date. */
                date?: components["parameters"]["DateQuery"];
            };
            header?: {
                /** @description Previously received `ETag`. The server answers `304` when the payload is unchanged. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                /** @description Building code, e.g. `A`. */
                code: components["parameters"]["BuildingCodePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board snapshot. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            304: components["responses"]["NotModified"];
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getTimeline: {
        parameters: {
            query?: {
                /** @description Local building date `YYYY-MM-DD`. Defaults to the building's current local date. */
                date?: components["parameters"]["DateQuery"];
            };
            header?: never;
            path: {
                /** @description Building code, e.g. `A`. */
                code: components["parameters"]["BuildingCodePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Day timeline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getRoomDay: {
        parameters: {
            query?: {
                /** @description Local building date `YYYY-MM-DD`. Defaults to the building's current local date. */
                date?: components["parameters"]["DateQuery"];
            };
            header?: never;
            path: {
                /** @description Room code, e.g. `213`, `WC-N1`, `CORE-S2`. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions of the room. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySessions"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getTeacherDay: {
        parameters: {
            query?: {
                /** @description Local building date `YYYY-MM-DD`. Defaults to the building's current local date. */
                date?: components["parameters"]["DateQuery"];
            };
            header?: never;
            path: {
                /** @description Teacher id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions of the teacher. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySessions"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getGroupDay: {
        parameters: {
            query?: {
                /** @description Local building date `YYYY-MM-DD`. Defaults to the building's current local date. */
                date?: components["parameters"]["DateQuery"];
            };
            header?: never;
            path: {
                /** @description Student group code, e.g. `ПО2308`. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions of the group. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySessions"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Search query (at least 1 character). */
                q: string;
                /** @description Maximum hits per kind. Defaults to 5. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search hits grouped by kind. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    streamEvents: {
        parameters: {
            query: {
                /** @description Building code to subscribe to. */
                building: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An open SSE stream. */
            200: {
                headers: {
                    /** @description Always `no-cache`. */
                    "Cache-Control"?: string;
                    /** @description Always `text/event-stream`. */
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getTime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server time and clock mode. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeInfo"];
                };
            };
        };
    };
    createOverride: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description The created override. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Override"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Override id returned by `createOverride`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Override deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createAnnouncement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnouncementRequest"];
            };
        };
        responses: {
            /** @description The created announcement. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
